### ISSUE TITLE
mariadb102u

### ISSUE THREAD

**Issue by i1tech** [iuscommunity/wishlist#177] opened 2018-02-01 17:06 UTC
### What new package do you want?

MariaDB 10.2.x

### Why?

MariaDB 10.2.x Stable (GA) is the latest stable release from MariaDB. Having this GA release available will allow Developers, DBA's and System Administrators to begin the work of deploying and testing in the development environment going forward. Many new features were added to include Windows function, InnoDB Tables now support Spacial Indexes, ed25519 based authentication plugin vs old insecure SHA1.

Many further features and enhancements can be found at:
https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-102/

### Testing

I agree to test the new package to ensure that it works as expected. I currently manage standalone and Galera Cluster based implementations of MariaDB 10.1.x in both development and production environments. We will need to obviously test these packages before upgrading our development and/or production environments, will be happy to post results, problems, workarounds, etc here for review and discussion.

**Comment by carlwgeorge** [comment] 2018-02-01 19:17
Duplicate of https://github.com/iuscommunity/wishlist/issues/138.

**Closed by carlwgeorge** 2018-02-01 19:17 UTC
