### ISSUE TITLE
php70u-pecl-redis

### ISSUE THREAD

**Issue by vasillalov** [iuscommunity/wishlist#66] opened 2016-05-20 14:20 UTC
### What package do you want?

php70u-pecl-redis

### Why?

Redis module is heavily used in PHP based applications. The upstream maintainer of PHP-PECL-REDIS has released a PHP7 branch here:  https://github.com/phpredis/phpredis.git. We've compiled this manually from source, it is stable and it works. However, an RPM package that is tied with the rest of php70u packages will simplify automated installs and upgrades.

### OS versions

I would like this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment] 2016-05-20 14:27
Howdy @vasillalov,

Thanks for your request, but this is a duplicate of #43.  Go ahead and subscribe to that issue so you can be notified of our progress.

**Closed by carlwgeorge** 2016-05-20 14:27 UTC

**Comment by vasillalov** [comment] 2016-05-20 14:36
Thank you for the quick reply and I apologize for creating a duplicate.
