### ISSUE TITLE
tomcat7 on RHEL/CentOS 6

### ISSUE THREAD

**Issue by nickbales** [iuscommunity/wishlist#25] opened 2015-11-23 15:04 UTC
While the jpackage repo does exist for this function, it is not very well maintained, and packages have had a history of introducing changes that are not backwards-compatible.

**Comment by b-harper** [comment] 2015-11-23 19:59
Hello @nickbales,

Thanks for taking the time to submit this request.  We use the following questions to help evaluate new packages requests:

* Is the new package a good fit for IUS?
* Will the new package be maintainable with our current resources?
* Is the requester willing to test the new package to ensure expected behaviour?

In EL6 tomcat is not provided by Red Hat, but is available in [EPEL][0].  The EPEL package has not been updated and is several versions behind.  There has been some [effort to get it updated][1], but it looks like determining which version of Java to use has stalled that effort.  IUS is for new versions of software that are a part of EL, while EPEL is got packages not part of EL.  While there had been exceptions, I tend to want to avoid packaging stuff that should be or is apart of EPEL.  Also IUS also 
tends to start packaging the most recent version and not the middle of the road version.    

Can you elaborate on the changes to the jpackage repo that caused backwards-compatible issues?  I am wondering if these were changing made to tomcat itself or just the way it got packaged.  

-Ben

[0]: https://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/tomcat.html
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1154978

**Comment by b-harper** [comment] 2015-11-23 21:04
I need to do a slight correction.  Red Hat does provide tomcat6 package in the base repos for RHEL6.    Even though this is the case, it still seems like getting the EPEL packages updated is a better approach.

**Comment by b-harper** [comment] 2015-12-03 17:02
Looking back at the [upgrade request bug][0], there have been some updates and thing are looking like they are moving ahead.  They just need to work out some dependencies issues.  

-Ben
[0]: https://bugzilla.redhat.com/show_bug.cgi?id=1154978

**Comment by b-harper** [comment] 2016-01-06 20:23
The [upgrade request bug][0] has been updated and [tomcat-7.0.65 has been submitted to EPEL 6].

[0]: https://bugzilla.redhat.com/show_bug.cgi?id=1154978
[1]: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-819f6356ea

**Comment by carlwgeorge** [comment] 2016-02-01 15:05
@nickbales Since the EPEL package has been updated, I'm going to go ahead and close this out.

**Closed by carlwgeorge** 2016-02-01 15:05 UTC
