### ISSUE TITLE
libmemcached-devel 10.0.18

### ISSUE THREAD

**Issue by swagopopotamus** [iuscommunity/wishlist#250] opened 2019-11-19 21:03 UTC
**What new package do you want?**

libmemcached-devel 10.0.18

**Why?**

The most recent version available in the RH and Cent repos is 10.0.16 and has several bugs. At least 1.0.18 is recommended in the latest PHP memcached extension versions

**Testing**

I agree to test the new package to ensure that it works as expected. Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment] 2019-11-19 21:06
duplicate of #249 (-devel comes from the same spec file)

**Closed as completed by carlwgeorge** 2019-11-19 21:06 UTC
