### ISSUE TITLE
httpd24u-mod_md

### ISSUE THREAD

**Issue by matyuvt** [iuscommunity/wishlist#193] opened 2018-04-05 08:19 UTC
### What new package do you want?

httpd24u-mod_md

### Why?

Available in version httpd 2.4.30 and later. This feature would be very
useful to me.
https://github.com/icing/mod_md/releases
http://httpd.apache.org/docs/2.4/mod/mod_md.html

### OS versions
Centos 6 , 7

### Testing
I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment] 2018-04-05 12:56
Duplicate of https://github.com/iuscommunity-pkg/httpd24u/issues/17.

**Closed by carlwgeorge** 2018-04-05 12:56 UTC
