### ISSUE TITLE
Provide git229 package

### ISSUE THREAD

**Issue by nkadel** [iuscommunity/wishlist#291] opened 2020-10-23 06:18 UTC
git229

got229 2.29.0

Git 2.29.0 is available with modest updates over the current git224 and associated git 2.24 package.

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

In fact, I'm already publishing a repo to build it, based on your git224 rrepo, at https://github.com/nkadel/nkadel-git229-srpm

**Comment by carlwgeorge** [comment] 2022-05-09 18:43
Duplicate of #297.

**Closed as completed by carlwgeorge** 2022-05-09 18:43 UTC
