### ISSUE TITLE
MariaDB 10.1 (mariadb101u)

### ISSUE THREAD

**Issue by Fale** [iuscommunity/wishlist#20] opened 2015-10-25 17:39 UTC
It's now GA and it would be a nice to have :) https://blog.mariadb.org/mariadb-10-1-is-stable-ga/

**Comment by b-harper** [comment] 2015-10-26 14:28
Hello @Fale,

Thanks for heads up.  I can't believe I missed that announcement.  We use the following to help evaluate new package requests:

Is the new package a good fit for IUS?
Will the new package be maintainable with our current resources?
Is the requester willing to test the new package to ensure expected behaviour?

Since we already package mariadb100u, it is clearly a good fit for IUS and should not add too much of a work load.  Would you be willing to test the packages?

-Ben

**Comment by Fale** [comment] 2015-10-26 14:29
Yes I would be glad to test it :)

**Comment by b-harper** [comment] 2015-10-26 15:06
Previous request regarding Galera for MariaDB 10.1, #5

**Comment by b-harper** [comment] 2015-10-28 16:36
@Fale, good to hear.  We will work on getting some packages in the testing repo as soon as we can.

**Comment by carlwgeorge** [comment] 2015-11-05 21:31
@Fale I have completed the process of [porting Fedora's mariadb 10.1 pacakge to IUS][1].  Initial mariadb101u packages should hit the [testing repositories][2] during tonight's automation.  We look forward to your feedback on their usability.

[1]: https://github.com/iuscommunity-pkg/mariadb101u
[2]: https://ius.io/Usage/#using-testing-repositories

**Comment by Fale** [comment] 2015-11-05 21:37
Thanks a lot, I'll test it over the weekend :)

**Comment by carlwgeorge** [comment] 2015-11-05 22:56
I noticed an issue with installation.  By default `mariadb-libs` is installed on EL7.  This means that you must erase `mariadb-libs` and install `mariadb101u-libs` in the same transaction.  If you want to go straight to having `mariadb101u-server` installed from stock, this command should work, but doesn't.

    yum swap -- erase mariadb-libs -- install mariadb101u-server

Alternatively, it can be accomplished with two commands.

    yum swap mariadb-libs mariadb101u-libs
    yum install mariadb101u-server

I think [this][1] is the problem.  It is resolving the requirement of `%{_sysconfdir}/my.cnf` and `%{_sysconfdir}/my.cnf.d` to stock `mariadb-libs` (even though the first transaction was explicitly asking to remove it).  If I replace those two lines with an explicit requirement on `mariadb101u-libs` then I think I can resolve this inconvenience.

Regardless, the second method works well enough to start testing.  Let me know how it goes and I'll work on that dependency fix.

[1]: https://github.com/iuscommunity-pkg/mariadb101u/blob/f15145081932a01b8bd20430cfe33159facebc18/SPECS/mariadb101u.spec#L333-L334

**Comment by carlwgeorge** [comment] 2015-11-12 14:32
The dependency fix is in `mariadb101u-10.1.8-2.ius`, which I moved to the testing repos this past weekend.  Have you had a chance to test this package out yet?

**Comment by kemra102** [comment] 2015-11-12 15:31
I will try to do some form of testing tonight.

**Comment by kemra102** [comment] 2015-11-12 20:28
It runs nicely as a single server once installed like so:

```bash
yum swap mariadb-libs mariadb101u-libs
yum install mariadb101u-server
```

However for the life of me I could not get the Galera component to start properly. Looks like a new script is available to do that but it has not been packaged yet: https://mariadb.atlassian.net/browse/MDEV-9007

**Comment by b-harper** [comment] 2015-11-12 23:57
Hey @kemra102 

Were you able to get the Galera stuff started with the updated *service.in, use_galera_new_cluster.conf and galera_new_cluster.sh files from the github pull request referenced in that bug?  

-Ben

**Comment by kemra102** [comment] 2015-11-13 00:01
@b-harper Not as yet, will give them all a try tomorrow evening.

**Comment by carlwgeorge** [comment] 2015-11-24 22:45
@kemra102 That upstream bug is marked as closed as of `10.1.9`.  We are in the process of updating the mariadb101u packages to that version, so I suggest waiting to test further until we have those done for you.

**Comment by carlwgeorge** [comment] 2015-11-25 03:00
@kemra102 `mariadb101u-10.1.9-1.ius` has been completed and will move to the testing repositories during tonight's automation.

**Comment by kemra102** [comment] 2015-11-25 19:14
@carlwgeorge Doesn't look like any files included in the pull request related to the closed issue are in the `10.1.9` release as they aren't installed on my test system running the `mariadb101u-10.1.9-1.ius` package.

**Comment by b-harper** [comment] 2015-11-30 22:45
@kemra102 Thanks for the feedback.  Somehow I missed those files.  We will look to get some updated packages into the testing repos soon.

**Comment by b-harper** [comment] 2015-12-04 22:46
After much research, tweaking, testing and trouble shooting, I was able to get a Galera Cluster up and running based on the mariadb101u packages in the testing repositories.  I used this [guide][0] to help get myself acquainted with setting up a Galera Cluster and with some changes got it working with the current IUS packages.  Here is what I did:

* created two CentOS 7 servers
* installed ius-release
* installed mariadb101u-server from ius-testing and glaera from EPEL on both server
* mess with firewalld to allow access between the servers
* started mariadb on both servers and added the sst_user from step 6 in the [guide][0]
* stopped mariadb on both servers
* Slight tweak from step 7 from the [guide][0], 'wsrep_on=ON' needs to get added to mariadb-server.cnf
* added ' $MYSQLD_OPTS' to the [this line][1] in the mariadb systemd file on one of the servers
* started mariadb on that same servers based on this [comment from the bug][2]
* start mariadb normally on the other server
* profit

All of this is really notes to myself about some of the changes that need to get added to our packages.  Some other changes like the mariadb@bootstrap will also need to get done.  




[0]: http://blog.laimbock.com/2014/07/08/howto-setup-mariadb-galera-cluster-10-on-centos/
[1]: https://github.com/iuscommunity-pkg/mariadb101u/blob/master/SOURCES/mysql.service.in#L39
[2]: https://mariadb.atlassian.net/browse/MDEV-9007?focusedCommentId=77113&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-77113

**Comment by b-harper** [comment] 2015-12-09 22:30
I am been looking into what (if any changes) we should make in regards to Galera support within mariadb101u.  We need a balanced approach for configurations with and without Galera.    From some of the research I have done, it appears that changes to my.cnf is needed in almost all use cases.  Seeing that is the case, how much should we change the mariadb101u packages to use Galera when some changes will be needed anyways.  

Should the mariadb101u-server package require the galera package?

Should the package provided systemd service files (under /usr/lib/systemd/system/) include the options to use 'MYSQLD_OPTS=--wsrep-new-cluster' option needed to start a new cluster?  Or should that be something a Galera user should customize (under /etc/systemd/system/)?

Is the galera_new_cluster script even really needed?  

Should we care about accommodating Percona users and include the mariadb@bootstrap service file that just echos instructions? 

@carlwgeorge and myself have been debating these questions.  We are curious what Fedora will do when they update their mariadb packages.  @kemra102, @Fale and others, what are your thoughts?

**Comment by Fale** [comment] 2015-12-18 11:23
On Wed, Dec 09, 2015 at 02:30:42PM -0800, b-harper wrote:
> I am been looking into what (if any changes) we should make in regards to Galera support within mariadb101u.  We need a balanced approach for configurations with and without Galera.    From some of the research I have done, it appears that changes to my.cnf is needed in almost all use cases.  Seeing that is the case, how much should we change the mariadb101u packages to use Galera when some changes will be needed anyways.  
> 
> Should the mariadb101u-server package require the galera package?

I'm not sure about this.
If we require the galera package, we will have a very different approach
from Fedora [0] and probably future versions of EL.
Also, very often MariaDB is used without galera.
In the other hand, it would make easier to setup a galera cluster.
 
> Should the package provided systemd service files (under /usr/lib/systemd/system/) include the options to use 'MYSQLD_OPTS=--wsrep-new-cluster' option needed to start a new cluster?  Or should that be something a Galera user should customize (under /etc/systemd/system/)?

I was speaking about this in the MariaDB channel about this few weeks
ago and the point of view of the people that partecipated in the
discussion was against the inclusion.
I think that we should make possible to run a cluster always using the
same command and therefore I'm in favor of the inclusion.
My point of view is that a package should have good defaults (99% of
users should have the thing working out of the box).

> Is the galera_new_cluster script even really needed?  

Probably it depends on the answer to the previous question.

> Should we care about accommodating Percona users and include the mariadb@bootstrap service file that just echos instructions? 

I'm pro automation (even more when it comes to server applications) so I
think that a service that echo instruction is pretty pointless.
Documentation is created for instructions, services are created to do
things.

[0] http://pkgs.fedoraproject.org/cgit/mariadb.git/tree/mariadb.spec

My2cc,
Fale

**Comment by b-harper** [comment] 2015-12-18 20:04
Hey @Fale,

Thanks for the feedback.  In general, I agree that there is wisdom in aligning IUS packages with Fedora/EL.  Fedora has yet to update to 10.1.9, which is the version that updated the systemd files.  This is why I asked for feedback.

We also received some feedback via email that was in support of not catering to Galera use cases.

Currently, I thinking we should keep the packages as is.  While I am not DBA,  it seems there is not a sane default configuration for Galera.  If that is the case. then we might as well leave all of the Galera configuration for the user and/or automation.  Maybe include a systemd service file with option to kick off the Galera under /usr/share/doc?  Maybe keep as is until Fedora updates?

-Ben

**Comment by carlwgeorge** [comment] 2015-12-18 21:52
I agree that we should let Fedora lead the way on this.  IUS can follow suit later.

**Comment by b-harper** [comment] 2016-01-08 22:10
We received [an issue ][0] for mariadb100u regarding some of the virtual provides.   I have applied [the same fix][1] and updated packages will be hitting the testing repos.  

@kemra102, I am curious your thoughts about catering to Galera users? 

@Fale, did you ever get a chance to do some testing?


[0]: https://github.com/iuscommunity-pkg/mariadb100u/issues/2
[1]: https://github.com/iuscommunity-pkg/mariadb101u/commit/3a6ea685b07dc70eade0cc6ae80eb9bf6ef2b3c5

**Comment by kemra102** [comment] 2016-01-10 23:59
@b-harper I think that the default config should be suitable for a stand alone MariaDB server. However there should probably still be a separate systemd unit file or a script that can set up a cluster assuming galera is also installed (mariadb-server probably shouldn't depend on galera - recommends perhaps) to make it very easy to get a galera cluster going.

**Comment by b-harper** [comment] 2016-01-11 16:02
@kemra102, thanks for the feedback.  Do you think including a systemd service file (with the needed bits to start a Galera cluster) within /usr/share would be sufficient?  The user would need to copy it to  /etc/systemd/system/ in order to use it.  

Unfortunately, RHEL does not yet have a way to handle recommends.  Maybe with the dnf package in EPEL7, but IUS does not require dnf.

**Comment by carlwgeorge** [comment] 2016-01-11 16:30
"recommends" is a [weak dependency](http://rpm.org/wiki/PackagerDocs/Dependencies#Weakdependencies).  That is implemented in rpm itself, not yum or dnf.  It was added in [rpm 4.12](https://fedoraproject.org/wiki/Changes/RPM-4.12#Detailed_Description).  RHEL 7 is still using rpm 4.11.

**Comment by kemra102** [comment] 2016-01-11 18:23
@b-harper I think that's a good starting point for where we are now.

**Comment by b-harper** [comment] 2016-01-19 23:01
I have built new packages based on 10.1.10 release and will hit the testing repos tomorrow.  No changes regarding Galera configuration have been made at this time.

**Comment by b-harper** [comment] 2016-01-28 23:06
[Fedora's mariadb git repository][0] finally got [an update][1].  The update is very minimal and does not address any the the concerns regarding Galera.  It will be curious to see if more updates will come and if they address Galera configuration.  Generally we prefer to follow Fedora/RHEL way of doing things, but not always.  Also, I want to to avoid releasing mariadb101u packages into the stable repositories and then make some major changes.  

-Ben

[0]: http://pkgs.fedoraproject.org/cgit/rpms/mariadb.git/
[1]: http://pkgs.fedoraproject.org/cgit/rpms/mariadb.git/commit/?id=9a948cc78e95d605445b26ade650e4ca612731f6

**Comment by b-harper** [comment] 2016-02-03 16:17
I have built new packages based on the 10.1.11 release and will hit the testing repositories tomorrow.  Seeing that Fedora is dragging its feet when it comes to MariaDB 10.1, I am thinking we might release our mariadb100u with no considerations for Galera (just like Fedora git repositories now).  Once in the stable repositories, It would be easier for was to add those bits than remove them.

**Comment by b-harper** [comment] 2016-02-11 22:41
[Fedora's mariadb git repository][0] has been updated with several changes to align with upstream.  All of my concerns regarding Galera have been address.  Updated packages have been built to align with Fedora and will hit the testing repositories after tonight's automation run.


[0]: http://pkgs.fedoraproject.org/cgit/rpms/mariadb.git/

**Comment by b-harper** [comment] 2016-02-15 19:49
Thanks to all who have given feedback.  Now that we have confirmation from Fedora regarding Galera configuration, we are going to proceed and move the packages into the stable repositories during tonight's automation run.

**Closed by b-harper** 2016-02-15 19:49 UTC
