### ISSUE TITLE
php72u-pecl-mcrypt

### ISSUE THREAD

**Issue by wiza** [iuscommunity/wishlist#215] opened 2018-10-23 18:20 UTC
### What new package do you want?

php72u-pecl-mcrypt

### Why?

It's removed from PHP but available from PECL and still used in many projects.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment] 2018-10-23 19:22
Duplicate of #179 and #190.  Please search existing issues (included closed ones) before requesting a package.

**Closed by carlwgeorge** 2018-10-23 19:22 UTC
