### ISSUE TITLE
php56u-twig

### ISSUE THREAD

**Issue by iler** [iuscommunity/wishlist#27] opened 2015-11-25 17:35 UTC
Would be great to have php56u-twig and php56u-twig-ctwig (https://github.com/twigphp/Twig) packages in IUS. Twig is used for example in Drupal 8 and the C extension brings some nice performance improvements in using Twig.

**Comment by james-nesbitt** [comment] 2015-11-26 08:47
+1

**Comment by jcnventura** [comment] 2015-11-26 08:52
Agree with @iler

**Comment by operinko** [comment] 2015-11-26 08:55
+1 from me too.

**Comment by remicollet** [comment] 2015-11-26 09:05
While I understand the need for this for compatibility with newer PHP api, I just need to raise your attention that any newer version than the one available in EPEL (1.22.2), will break lot of things available in EPEL (at least Symfony and all packages using symfony).

**Comment by b-harper** [comment] 2015-11-30 23:49
Hey everyone,

Thanks for taking the time to submit this request or give your thoughts.  We use the following questions to help evaluate requests:

* Is the new package a good fit for IUS?
* Will the new package be maintainable with our current resources?
* Is the requester willing to test the new package to ensure expected behaviour?

We will need to look into the first two questions.  An add-on or module for a version of PHP we package is common, but @remicollet brings up a great point.  (Thanks @remicollet) The ius-release package and some IUS packages do require EPEL, so it is important that IUS packages play nicely with EPEL.  We will also need to look at requirements.  We will update this issue when we have more information. 

-Ben

**Comment by carlwgeorge** [comment] 2015-12-01 19:41
In Fedora and EPEL, php-twig-ctwig is provided by the main php-twig package.  Updating title for clarity.

**Comment by carlwgeorge** [comment] 2015-12-01 20:43
@remicollet Can you elaborate on the potential breakage you are describing?  I created some super quick test packages, made them available in a local repo, and yum correctly resolved EPEL's php-twig to fill the dependency for php-symfony.

```
# yum -e10 -d10 install php-symfony
```
```
php-symfony-2.5.12-1.el7.noarch requires: php-composer(symfony/twig-bridge) = 2.5.12
--> Processing Dependency: php-composer(symfony/twig-bridge) = 2.5.12 for package: php-symfony-2.5.12-1.el7.noarch
Searching pkgSack for dep: php-composer(symfony/twig-bridge)
TSINFO: Marking php-symfony-twig-bridge-2.5.12-1.el7.noarch as install for php-symfony-2.5.12-1.el7.noarch
```
```
php-symfony-twig-bridge-2.5.12-1.el7.noarch requires: php-composer(twig/twig) < 2.0
--> Processing Dependency: php-composer(twig/twig) < 2.0 for package: php-symfony-twig-bridge-2.5.12-1.el7.noarch
Searching pkgSack for dep: php-composer(twig/twig)
TSINFO: Marking php-twig-1.22.2-1.el7.x86_64 as install for php-symfony-twig-bridge-2.5.12-1.el7.noarch
```
```
# repoquery --whatprovides php-twig
php-twig-0:1.22.2-1.el7.x86_64
php56u-twig-0:1.23.1-0.1.ius.el7.centos.x86_64
```
```
# repoquery --whatprovides 'php-composer(twig/twig)'
php-twig-0:1.22.2-1.el7.x86_64
php56u-twig-0:1.23.1-0.1.ius.el7.centos.x86_64
```

I'm not seeing an issue here.

**Comment by remicollet** [comment] 2015-12-02 05:54
@carlwgeorge as I said, if you provide the same version 1.22 than EPEL, no issue with packages in EPEL.

But newer versions exists

* version 1.23 breaks symfony and introduce a API change which also break php-twig-extensions
* version 1.23.1 restore API (fixed by me), but still break symfony

Notice: as those are unexpected, dependencies (twig >1.20, <2) are not enough to prevent the update.

Now, last version of symfony 2.7.7, 2.8 and 3.0 requires twig > 1.23.

So,  "composer" users won't be able to use version 1.22

The reason why we use [Koschei](https://apps.fedoraproject.org/koschei/groups/php?order_by=state%2C-started) to monitor the PHP stack and detect such breakage.

**Comment by carlwgeorge** [comment] 2015-12-02 14:31
##### EPEL6
```
%global github_version   2.3.31
%global twig_min_ver 1.12.3
%global twig_max_ver 2.0
```
##### EPEL7
```
%global github_version   2.7.7
%global twig_min_ver 1.23
%global twig_max_ver 3
```

So if I'm understanding this correctly, this isn't an issue for EPEL7, and EPEL6 spec file needs to be updated to set `twig_max_ver` to 1.23?

**Comment by iler** [comment] 2016-01-05 12:17
Just checking if there is any progress with this?

**Comment by carlwgeorge** [comment] 2016-01-05 17:06
Hey @iler, I've got a spec file mostly finished.  I will try to finish it today so it can go into the testing repos for you to check out.

**Comment by carlwgeorge** [comment] 2016-01-10 20:55
Sorry for the delay.  Initial builds have been completed and will move to our [testing repositories](https://ius.io/Usage/#using-testing-repositories) during tonight's automation.  We look forward to your feedback on them.

**Comment by iler** [comment] 2016-01-11 07:45
@carlwgeorge thanks! Will test it and provide feedback on the results.

**Comment by carlwgeorge** [comment] 2016-02-01 14:53
@iler How did those packages work out for you?

**Comment by iler** [comment] 2016-02-08 10:10
@carlwgeorge we have added this to our environment builds and we have not faced any problems with it. So I would say it's good to go :)

**Comment by carlwgeorge** [comment] 2016-02-08 14:39
Thanks for the feedback.  I'll tag these packages to move to the stable repositories during tonight's automation.

**Closed by carlwgeorge** 2016-02-08 14:39 UTC
Labels: php56u
